<% db = URI.parse(ENV['DATABASE_URL']) %>
development:
  adapter: postgres
  database: <%= File.basename(db.path) %>
  username: <%= db.user %>
  password: <%= db.password %>
  host: <%= db.host %>
  reconnect: true
  pool: 25

test:
  adapter: postgres
  database: <%= File.basename(db.path) %>_test
  username: <%= db.user %>
  password: <%= db.password %>
  host: <%= db.host %>

production:
  adapter: postgres
  database: <%= File.basename(db.path) %>
  username: <%= db.user %>
  password: <%= db.password %>
  host: <%= db.host %>
  reconnect: true
  pool: 25
